//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErrorMachineManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class padmc_errortotal
    {
        public string mc_id { get; set; }
        public string device_id { get; set; }
        public Nullable<System.DateTime> error_date { get; set; }
        public Nullable<int> error_count { get; set; }
        public Nullable<int> error_timeelapse { get; set; }
    }
}
