//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErrorMachineManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class padmc_errordevice
    {
        public string device_name { get; set; }
        public string device_descrition { get; set; }
        public string device_errorname { get; set; }
        public string device_solution { get; set; }
    }
}
