//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErrorMachineManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class padmc_leader
    {
        public int leader_id { get; set; }
        public string leader_name { get; set; }
        public string leader_gen { get; set; }
        public string leader_phone { get; set; }
        public string leader_type { get; set; }
    }
}
