//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErrorMachineManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class padmc_error
    {
        public long id { get; set; }
        public string mc_id { get; set; }
        public string device_id { get; set; }
        public System.DateTime error_time { get; set; }
        public System.DateTime error_timereset { get; set; }
    }
}
