//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErrorMachineManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class padmc_machines
    {
        public string mc_id { get; set; }
        public string mc_name { get; set; }
        public Nullable<int> line_id { get; set; }
        public string mc_ip { get; set; }
        public string mc_process { get; set; }
        public Nullable<int> leader_id { get; set; }
        public string mc_plcname { get; set; }
        public string mc_devicekey { get; set; }
        public Nullable<int> mc_devicekey_status { get; set; }
    }
}
